### ISSUE TITLE
How to install "LBvh"?

### ISSUE THREAD

**Issue by yang-si-hang** [lyd405121/PBD#1]
How to install "LBvh"?

In the Mesh2Particle.py Line 11: import LBvh as LBvh
I can't find the "LBvh" python library on the internet. Can you tell me how to install "LBvh"?

**Comment by lyd405121** [comment]
Here is the code
https://github.com/lyd405121/PBD/blob/main/accel/LBvh.py

**Comment by yang-si-hang** [comment]
Thank you!
